### ISSUE TITLE
Naming remark for ProblemFactory

### ISSUE THREAD

**Issue by bchretien** [roboptim/roboptim-core-manifold#10]
The name used for `ProblemFactory` in the `roboptim` namespace is quite misleading, since this is directly related to manifolds.

Also, try not to include `*.hxx` inside a namespace (like [here](https://github.com/roboptim/roboptim-core-manifold/blob/master/include/roboptim/core/manifold-map/decorator/problem-factory.hh#L108)).

**Comment by fdarricau** [comment]
Do you think we should name it ManifoldProblem, ManifoldProblemFactory or something like that ?

As for the .hxx in the namespace, I must have missed that one, as I especially tried to track down the remaining ones.

**Comment by bchretien** [comment]
`ManifoldProblemFactory` may be clearer I think: it's a factory to build a problem on manifolds.

While we're at it, the multiple [macros](https://github.com/roboptim/roboptim-core-manifold/blob/7c8ae8b53d568cd405a18f0f1a22ed8a0b4e6dfd/include/roboptim/core/manifold-map/decorator/manifold-map.hh#L33-L53) should also have their names starting with `ROBOPTIM_`, especially if they're likely to be used outside of the package. This makes the origin of the macro slightly clearer, and prevents clashes.

**Comment by Delca** [comment]
Fixed in [this commit](https://github.com/roboptim/roboptim-core-manifold/commit/066874ab934ffeb3e38d8cb46cf274f346908244)

**Comment by bchretien** [comment]
:+1:
