### ISSUE TITLE
Generating an empty problem crashes the program

### ISSUE THREAD

**Issue by Delca** [roboptim/roboptim-core-manifold#9]
Because we try to create the default constraint from the accumulated manifolds, if no constraints were added to the problem, the generated manifold has a size of 0, causing the RobOptim assert in the function's constructor to end the execution.
The simplest workaround is to check the size of the manifold so as to display an error message from our side of the code.

**Comment by fdarricau** [comment]
Erratum, it is when we create a default objective function that the assert spawns.

**Comment by fdarricau** [comment]
Fixed in [this commit](https://github.com/roboptim/roboptim-core-manifold/commit/850e0eb66c679e051c0f30cf642a39c161516e36)
